### ISSUE TITLE
Question Headings for Navigation Panel 

### ISSUE THREAD

**Issue by AnubhavDhingra** [CCALI/A2JViewer#107]
This would require a bigger refactor than previously thought. 
There are a couple of macros being used in the `navigation.js` that will also be required for the navigation-panel.  Will be creating a single helper file with the macros to be used in both `navigation.js` and `navigation-panel.js`.
There is a dependancy on `logic/tLogic` in the macros and resolving that might take time.

**Comment by janebitovi** [comment]
This issue doesn't mention what the problem was.

Likely this was in reference to page repeat vars (and derived values like "FIRST") not staying tied to the specific instance of the historical visited page titles, which was indeed a bigger task than anyone might have expected, but this is fixed and in production

closing
