### ISSUE TITLE
Slideout Content to restore it's last state for an interview

### ISSUE THREAD

**Issue by AnubhavDhingra** [CCALI/A2JViewer#134]
The last state of the Slideout Content (Debug Panel) to be restored for the user, when they go back into preview after stepping out of it for the same interview.

Possible States :
- Slideout Closed
- Slideout Open 
     - Debug Panel (variables list and logs)
     - Advance Nav Panel

**Comment by janebitovi** [comment]
Looks like this can be closed:

Adv nav restores everything with answers,
author preview maintains state between individual page previews
(the main preview option resets the state still by design)

The interview itself has a "Show Adv Nav" option that will determine if that interview should show the Adv Nav by default too.
